version: '2.3'

services:
  depot:
    build:
      context: .
      target: release
    image: local/depot
    restart: always
    command: "rails server -b 0.0.0.0"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=depot
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=depot
    restart: always

  redis:
    image: redis:4-alpine
    restart: always
